// <auto-generated />
using GrupoSYM.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GrupoSYM.Migrations
{
    [DbContext(typeof(SymContext))]
    [Migration("20210531152630_CreateRelationship")]
    partial class CreateRelationship
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("GrupoSYM.Models.Consultorio", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("ID");

                    b.ToTable("consultorios");
                });

            modelBuilder.Entity("GrupoSYM.Models.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("CRM")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("ValorConsulta")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("medicos");
                });

            modelBuilder.Entity("GrupoSYM.Models.MedicoConsultorio", b =>
                {
                    b.Property<int>("MedicoId")
                        .HasColumnType("int")
                        .HasColumnName("medicoId");

                    b.Property<int>("ConsultorioId")
                        .HasColumnType("int")
                        .HasColumnName("consultorioId");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.HasKey("MedicoId", "ConsultorioId");

                    b.HasIndex("ConsultorioId");

                    b.ToTable("medicosconsultorios");
                });

            modelBuilder.Entity("GrupoSYM.Models.MedicoConsultorio", b =>
                {
                    b.HasOne("GrupoSYM.Models.Consultorio", "Consultorio")
                        .WithMany("MedicoConsultorios")
                        .HasForeignKey("ConsultorioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GrupoSYM.Models.Medico", "Medico")
                        .WithMany("MedicosConsultorio")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Consultorio");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("GrupoSYM.Models.Consultorio", b =>
                {
                    b.Navigation("MedicoConsultorios");
                });

            modelBuilder.Entity("GrupoSYM.Models.Medico", b =>
                {
                    b.Navigation("MedicosConsultorio");
                });
#pragma warning restore 612, 618
        }
    }
}
