// <auto-generated />
using GrupoSYM.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GrupoSYM.Migrations
{
    [DbContext(typeof(SymContext))]
    partial class SymContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("GrupoSYM.Models.Medico", b =>
                {
                    b.Property<string>("CRM")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("ValorConsulta")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("CRM");

                    b.ToTable("Medicos");
                });
#pragma warning restore 612, 618
        }
    }
}
